# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Run: bundle exec jekyll serve --watch#
title: 刘玉宝(Liu Yubao)的博客
email: yubaoliu89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Yubao's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yubaoliu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
rss_url: /pages/feed.xml

# Build settings
markdown: kramdown
#theme: classic-jekyll-theme
highlighter: rouge #gem install rouge

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter:  #twitter_username:
weibo:
github: yubaoliu #github_username:  yubaoliu
instagram:
linkedin: https://www.linkedin.com/in/yubao-liu-1022b7120/
permalink: /:categories/:year/:month/:day/:title.html


# avatar and Favicon
avatar: /assets/img/avatar.png
favicon: /assets/img/qrcode.jpg

#Plugin Setting
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

# disqus config
disqus:
  shortname: https-yubaoliu-github-io
  page_path: https://yubaoliu.github.io
  page_title: yubao-blog
comments: true
#disqus: https-yubaoliu-github-io

# google analytics config
ga:
  id: UA-131527698-1
  url: yubaoliu.github.io

sass:
  style: compressed


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Liu Yubao
#      toc: true
  -
    scope:
      path: "_posts/Math"
    values:
      categories: Math
  -
     scope:
       path: "_posts/Tools"
     values:
       categories: Tools
  -
     scope:
       path: "_posts/AI"
     values:
       categories: AI
  -
     scope:
       path: "_posts/WebDev"
     values:
       categories: WebDev

  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
